name: Windows Build Only

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM/Clang
        run: choco install llvm -y

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen --version 1.80.1

      - name: Build Windows Executable
        run: |
          flutter pub get
          flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RustDesk-Windows-Soul
          path: build/windows/runner/Release/