name: Windows Build Only

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Windows Executable
        run: |
          cargo build --release
          flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RustDesk-Windows-Soul
          path: build/windows/runner/Release/